<?php

namespace ContainerK5j0VgE;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlgorithmeControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\BackEnd\AlgorithmeController' shared autowired service.
     *
     * @return \App\Controller\BackEnd\AlgorithmeController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\BackEnd\\AlgorithmeController'] = $instance = new \App\Controller\BackEnd\AlgorithmeController();

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\BackEnd\\AlgorithmeController', $container));

        return $instance;
    }
}
