<?php

namespace ContainerXaHIyYP;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlgorithmeControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\BackEnd\AlgorithmeController' shared autowired service.
     *
     * @return \App\Controller\BackEnd\AlgorithmeController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'BackEnd'.\DIRECTORY_SEPARATOR.'AlgorithmeController.php';

        $container->services['App\\Controller\\BackEnd\\AlgorithmeController'] = $instance = new \App\Controller\BackEnd\AlgorithmeController();

        $instance->setContainer(($container->privates['.service_locator.W9y3dzm'] ?? $container->load('get_ServiceLocator_W9y3dzmService'))->withContext('App\\Controller\\BackEnd\\AlgorithmeController', $container));

        return $instance;
    }
}
