<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerK5j0VgE\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerK5j0VgE/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerK5j0VgE.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerK5j0VgE\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerK5j0VgE\App_KernelProdContainer([
    'container.build_hash' => 'K5j0VgE',
    'container.build_id' => '54826bba',
    'container.build_time' => 1634241630,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerK5j0VgE');
