<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX8hWnhS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX8hWnhS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX8hWnhS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX8hWnhS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX8hWnhS\App_KernelDevDebugContainer([
    'container.build_hash' => 'X8hWnhS',
    'container.build_id' => 'cca17e10',
    'container.build_time' => 1634888017,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX8hWnhS');
