<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXaHIyYP\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXaHIyYP/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXaHIyYP.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXaHIyYP\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXaHIyYP\App_KernelDevDebugContainer([
    'container.build_hash' => 'XaHIyYP',
    'container.build_id' => 'ae075dfb',
    'container.build_time' => 1634247456,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXaHIyYP');
